version: "3.7"
services:
  pgadmin:
    container_name: "pgadmin_container_prisma"
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "dba@fabulas.io"
      PGADMIN_DEFAULT_PASSWORD: "fabulas"
      SERVER_PORT: 5050
    ports:
      - "5050:80"
    restart: unless-stopped
  postgres:
    image: postgres:10.11
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fabulas
      POSTGRES_PASSWORD: fabulas
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  pgadmin:
